# Generated by Django 3.2.5 on 2021-09-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_usersmodel_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('startDate', models.DateField(blank=True, verbose_name='Начало')),
                ('endDate', models.DateField(blank=True, verbose_name='Конец')),
                ('status', models.CharField(choices=[('INCOMING', 'Не прочитано'), ('IN_PROGRESS', 'Выполняется'), ('COMPLETE', 'Завершена'), ('CANCLE', 'Отменена'), ('WAIT', 'Ожидает')], default=False, max_length=100, verbose_name='Завершено')),
                ('file_id', models.CharField(choices=[('INCOMING', 'Не прочитано'), ('IN_PROGRESS', 'Выполняется'), ('COMPLETE', 'Завершена'), ('CANCLE', 'Отменена'), ('WAIT', 'Ожидает')], default=False, max_length=100, verbose_name='Файл')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='users.usersmodel', verbose_name='Исполнитель')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='users.usersmodel', verbose_name='Поставщик')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher', to='users.usersmodel', verbose_name='Наблюдатель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=-1, max_length=100, verbose_name='Комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersmodel')),
            ],
            options={
                'verbose_name': 'Обощение тура',
                'verbose_name_plural': 'Обощение тура',
            },
        ),
    ]
