# Generated by Django 3.2.4 on 2021-06-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210615_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.CharField(default=-1, max_length=100, verbose_name='ID файла')),
                ('date', models.DateField(blank=True, verbose_name='Создан')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersmodel', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=-1, max_length=100, verbose_name='Описание')),
                ('startDate', models.DateField(blank=True, verbose_name='Начало')),
                ('endDate', models.DateField(blank=True, verbose_name='Конец')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.filemodel')),
            ],
            options={
                'verbose_name': 'Обощение тура',
                'verbose_name_plural': 'Обощение тура',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationUsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply', models.BooleanField(default=False, verbose_name='Принят')),
                ('endeed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reconciliationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersmodel')),
            ],
            options={
                'verbose_name': 'Обощение тура',
                'verbose_name_plural': 'Обощение тура',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=-1, max_length=100, verbose_name='Комментарий')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reconciliationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersmodel')),
            ],
            options={
                'verbose_name': 'Обощение тура',
                'verbose_name_plural': 'Обощение тура',
            },
        ),
    ]
