# Generated by Django 3.2.4 on 2021-06-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconciliationmodel',
            options={'verbose_name': 'Согласование', 'verbose_name_plural': 'Согласование'},
        ),
        migrations.AlterModelOptions(
            name='reconciliationusersmodel',
            options={'verbose_name': 'Пользователи согласования', 'verbose_name_plural': 'Пользователи согласования'},
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file',
            field=models.ImageField(default=1, upload_to='file', verbose_name='Файл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='fileId',
            field=models.CharField(max_length=100, verbose_name='ID файла'),
        ),
        migrations.AlterField(
            model_name='reconciliationmodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание'),
        ),
    ]
