# Generated by Django 3.2.5 on 2021-09-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210702_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmodel',
            name='encrypted',
            field=models.BooleanField(default=False, verbose_name='Зашифрован'),
        ),
    ]
