# Generated by Django 3.2.5 on 2021-09-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersmodel_role'),
        ('catalog', '0005_reconciliationmodel_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('fileId', models.CharField(max_length=100, verbose_name='ID файла')),
                ('date', models.DateField(blank=True, verbose_name='Создан')),
                ('file', models.FileField(blank=True, upload_to='images/files/', verbose_name='Файл')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersmodel', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
    ]
