# Generated by Django 3.2.5 on 2021-09-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_templatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Создан'),
        ),
    ]
