# Generated by Django 3.2.5 on 2021-09-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210916_0904'),
        ('catalog', '0008_auto_20210916_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmodel',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to='users.usersmodel', verbose_name='Организовал'),
        ),
    ]
