# Generated by Django 3.2.5 on 2021-09-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_reconciliationmodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemodel',
            name='fileId',
        ),
    ]
