# Generated by Django 3.2.5 on 2021-09-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_templatemodel_fileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.filemodel'),
        ),
    ]
