# Generated by Django 3.2.5 on 2021-09-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_templatemodel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100, verbose_name='Тип')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.filemodel', verbose_name='Файл')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reconciliationmodel', verbose_name='Согласование')),
            ],
            options={
                'verbose_name': 'Файл согласования',
                'verbose_name_plural': 'Файлы согласования',
            },
        ),
    ]
