# Generated by Django 3.2.5 on 2021-09-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_reconciliationfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='encrypted',
            field=models.BooleanField(default=False, verbose_name='Зашифрован'),
        ),
    ]
