# Generated by Django 3.2.4 on 2021-06-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=-1, max_length=100, verbose_name='Название')),
                ('description', models.CharField(default=-1, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('secondname', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Номер телефона')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'ользователи',
            },
        ),
        migrations.CreateModel(
            name='DepartamentUsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.departamentsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersmodel')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.AddField(
            model_name='departamentsmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersmodel', verbose_name='Руководитель'),
        ),
    ]
