# Generated by Django 3.2.4 on 2021-06-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentusersmodel',
            options={'verbose_name': 'Пользователи по отделам', 'verbose_name_plural': 'Пользователи по отделам'},
        ),
        migrations.AlterModelOptions(
            name='usersmodel',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='departamentsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='departamentsmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
