# Generated by Django 3.2.4 on 2021-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210615_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Токен'),
        ),
    ]
