# Generated by Django 3.2.4 on 2021-07-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210616_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='image',
            field=models.FileField(blank=True, upload_to='images/users/', verbose_name='Фото'),
        ),
    ]
