# Generated by Django 3.2.5 on 2021-09-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='role',
            field=models.CharField(blank=True, choices=[('ceo', 'Руководитель организации'), ('sign', 'Сотрудники, которые подписывают договора по доверенности'), ('contract', 'Сотрудники отдела Контрактной службы'), ('buh', 'Сотрудники Бухгалтерии и Планово-финансового управления'), ('loyer', 'Сотрудники Юридической службы'), ('manager', 'Руководители подразделений'), ('delo', 'Делопроизво-дитель'), ('admin', 'Администратор')], max_length=100, verbose_name='Роль'),
        ),
    ]
