# Generated by Django 3.2.5 on 2021-09-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersmodel_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='role',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='role',
            field=models.ManyToManyField(blank=True, to='users.RolesModel', verbose_name='Роль'),
        ),
    ]
